### ISSUE TITLE
Run tmt tests

### ISSUE THREAD

**Issue by nikic** [fedora-llvm-team/llvm-snapshots#59]
I'm wondering whether we should try to run tmt tests on snapshots. The way I see this working is that after forking into llvm-snapshots we would run the tests for one fedora version in a corresponding container on Github Actions.

Possibly the overall approach could be that we move out the snapshot promotion out of fedora-copr-build into check-todays-snapshot, doing something like this:

- [x] Check whether any build has failed (until now). If so, open an issue. (Same as now.)
- [ ] Check whether all builds succeeded. If so, perform the llvm-snapshots fork. (Similar to now, but happens as soon as builds are done, not the next day.)
- [ ] Run tmt tests for one configuration. If they fail, open an issue. (Or initially don't do anything, until we know that the tests actually work.)

We could also swap the last two points, which means that we would only fork to llvm-snapshots if tmt tests pass as well. We'd probably need some experience with how often / why they fail first.

**Comment by kwk** [comment]
@nikic thank you for these ideas.

# About tmt tests

Why can't we run tmt tests in the incubator project? Because it is not the final place to consume from? I think for the most part this is negligible. 

# About forking earlier

I agree that we could potentially fork into the `llvm-snapshots` on copr repository earlier than at the end of the day. While this sounds nice on paper we have to consider several things:

1. People who consume our snapshots in their CI jobs have worked with this schedule for a longer period of time and are fine with it.
2. If we fork earlier and at a potentially more random point time, we might interrupt ongoing installs.
3. Note that after the fork process we have some time in which the [repository metadata on Copr needs to be regenerated](https://github.com/kwk/llvm-daily-fedora-rpms/blob/30b13e7ef3d62dc917ab4c75ebe239943cdaada5/.github/workflows/fedora-copr-build.yml#L180-L185). That is an asynchronous and I think long running operation.

I'll try to get more information about the time this all takes in Copr from the `#copr` team. Then we can decide if the downtime would be acceptable to have during the day.

**Comment by nikic** [comment]
> Why can't we run tmt tests in the incubator project? Because it is not the final place to consume from? I think for the most part this is negligible.

I don't think it matters on which repo they run. I was mainly thinking in terms of how to implement the process so they run exactly once, so doing it during the promotion seemed like a good idea. But if running them on the incubator project is easier that should be totally fine.

As to forking, that's a good concern. I think something to keep in mind is that it's always day *somewhere* -- the middle of the night for us is probably day time on the west coast. You're right though that at least the current time is very predictable.

**Comment by kwk** [comment]
> I don't think it matters on which repo they run. I was mainly thinking in terms of how to implement the process so they run exactly once, so doing it during the promotion seemed like a good idea. But if running them on the incubator project is easier that should be totally fine.

Okay.
 
> As to forking, that's a good concern. I think something to keep in mind is that it's always day _somewhere_ -- the middle of the night for us is probably day time on the west coast. You're right though that at least the current time is very predictable.

Right, that's the only part I meant. Predictability.

I found out from the `#copr` team that it can take up to 15 minutes to regenerate the repositories. This is a ticket that may help in the future to inspect status of such actions in Copr: https://github.com/fedora-copr/copr/issues/1108

**Comment by kwk** [comment]
Sorry for the late update. I didn't follow along our chat internally but apparently the forking takes 1 hour.

**Comment by kwk** [comment]
@nikic I began working on this here: https://github.com/kwk/llvm-daily-fedora-rpms/blob/main/.github/workflows/tmt.yml . Once the workflow is free from systematic errors I think we can discuss how and when we wanna trigger it.

**Comment by nikic** [comment]
I believe that limit only applies to private repos.

**Comment by kwk** [comment]
We do run testing-farm now and I think this issue can be closed. Currently the testing-farm results are not gating things because they need fixing. We're working on having the tests green by default and only report on real errors.

**Comment by nikic** [comment]
Agree that this can be closed now. Thanks for your awesome work on this, the end result is really great!
